santoshi
Snehal-113/MI-9-MEAN pull request #11
Opened 2020-11-10 11:20 UTC by santoshinawkhare

2020-11-10 11:21 UTC, pradip1324 approved these changes

2020-11-10 12:35 UTC, Pawan1005 requested changes
never use h1 tag in head tag
add new line at end in every file

2020-11-11 12:07 UTC, Pawan1005 requested changes
1. follow HTML rules
2. add new line at the end

2020-11-17 05:11 UTC, Pawan1005 requested changes

2020-11-17 05:11 UTC, Pawan1005 commented on assignment5.html
> +                <li>Cooking, Reading. </li>
add hobbies there

2020-11-17 05:11 UTC, Pawan1005 commented on assignment5.html
> +</html>
add new line here

2020-11-17 11:42 UTC, pradip1324 approved these changes

2020-11-27 10:24 UTC, Pawan1005 approved these changes

2020-11-27 10:52 UTC, merged