Preeti- added user route list
Snehal-113/MI-9-MEAN pull request #140
Opened 2021-01-03 15:22 UTC by preetipie22

2021-01-04 05:48 UTC, Erhruday requested changes

2021-01-04 05:48 UTC, Erhruday commented on Projects/Team2/userRouteList.html
> +        <table class="table table-striped my-5">
use hover effect on table rows...

2021-01-04 05:48 UTC, Erhruday commented on Projects/Team2/userRouteList.html
> +                        <h4>HOME</h4>
plese use logo in all pages...

2021-01-07 12:24 UTC, Snehal-113 approved these changes

2021-01-07 12:24 UTC, Snehal-113 commented on Assignments/Javascript/PreetiA1_1(method2).html
> +        c = a + b;
this has to be without temporary variable
a=a+b;
b=a-b;
a=a-b;

2021-01-07 12:24 UTC, Snehal-113 commented on Assignments/Javascript/PreetiA2_2.html
> +            break;
case 0: 
            case 1: 
            case 2: 
            case 3: document.getElementById("grade").value = "F";
            break;

2021-01-07 12:24 UTC, Snehal-113 commented on Assignments/Javascript/PreetiA2_2.html
> +            break;
or 
 case 0: document.getElementById("grade").value = "F";break;
            case 1: document.getElementById("grade").value = "F";break;
            case 2: document.getElementById("grade").value = "F";break;
            case 3: document.getElementById("grade").value = "F";
            break;

2021-01-07 12:24 UTC, Snehal-113 commented on Assignments/Javascript/PreetiA3_1.html
> +                    document.write("leap");
use alert instead of document.write so that the previous html components are not replaced by document.write

2021-01-12 06:09 UTC, Pawan1005 approved these changes

2021-01-22 03:22 UTC, merged