Preeti
Snehal-113/MI-9-MEAN pull request #210
Opened 2021-02-08 09:54 UTC by preetipie22

2021-02-09 09:38 UTC, Snehal-113 requested changes

2021-02-09 09:38 UTC, Snehal-113 commented on Assignments/Javascript/Preeti/PreetiA19_1.html
> +                    document.write(x + "*" + i + "=" + res + "<br>");
use a p tag to display the result.

2021-02-09 10:22 UTC, preetipie22 commented on Assignments/Javascript/Preeti/PreetiA19_1.html
> +                    document.write(x + "*" + i + "=" + res + "<br>");
> use a p tag to display the result.

done

2021-02-22 09:52 UTC, Pawan1005 approved these changes

2021-02-28 06:33 UTC, merged