Added React Assignments
Snehal-113/MI-9-MEAN pull request #226
Opened 2021-03-03 08:09 UTC by Shubhangimamulkar

2021-03-03 19:19 UTC, Snehal-113 requested changes

2021-03-03 19:19 UTC, Snehal-113 commented on Assignments/REACT/Shubhangi_React/Shubhangi_A3.js
> +
ReactDom.render(<greeting />, document.getElementById("root"));

2021-03-03 19:19 UTC, Snehal-113 commented on Assignments/REACT/Shubhangi_React/Shubhangi_A6.js
> +setInterval(ShowTime,1000);
remove this block.Also add import statements

2021-03-04 04:41 UTC, Erhruday approved these changes
GooD..

2021-03-04 04:42 UTC, Snehal-113 approved these changes

2021-03-04 04:42 UTC, merged