Yashu
Snehal-113/MI-9-MEAN pull request #288
Opened 2021-03-30 12:19 UTC by yashubari

2021-04-06 12:18 UTC, Snehal-113 requested changes
The index.js file must be in src folder

2021-04-08 06:41 UTC, shivnanda6272 reviewed
Q6 :-  state IS NULL

2021-04-08 06:44 UTC, shivnanda6272 commented
> Q6 :- state IS NULL

2021-04-08 10:59 UTC, Snehal-113 requested changes

2021-04-08 10:59 UTC, Snehal-113 commented on Assignments/MYSQL/Yashasvi/YashasviDB1.sql
> +WHERE state=NULL;
state is null

2021-04-08 11:23 UTC, Snehal-113 approved these changes

2021-04-08 11:24 UTC, merged