added sql assignment 1 and 2
Snehal-113/MI-9-MEAN pull request #296
Opened 2021-04-05 11:17 UTC by preetipie22

2021-04-05 11:33 UTC, shivling123 approved these changes

2021-04-05 12:26 UTC, Erhruday approved these changes

2021-04-06 18:45 UTC, Snehal-113 requested changes

2021-04-06 18:45 UTC, Snehal-113 commented on Assignments/SQL/A2.sql
> +SELECT * FROM employees WHERE firstName LIKE '%F';
LIKE 'F%';

2021-04-06 18:45 UTC, Snehal-113 commented on Assignments/SQL/A2.sql
> +SELECT * FROM employees WHERE firstName LIKE '______' AND lastName LIKE 'n%';
firstName LIKE '______' AND lastName LIKE  '%n';

2021-04-07 04:01 UTC, Snehal-113 approved these changes

2021-04-07 04:01 UTC, merged