File added :MYSQL assignments 1,2,3
Snehal-113/MI-9-MEAN pull request #303
Opened 2021-04-07 06:26 UTC by Priyankashelke2411

2021-04-07 07:00 UTC, shivnanda6272 approved these changes

2021-04-07 11:53 UTC, Snehal-113 requested changes

2021-04-07 11:53 UTC, Snehal-113 commented on Assignments/MYSQL/Priyanka/PriyankaDB1_1.sql
> +WHERE state = null;
state IS NULL;

2021-04-07 11:53 UTC, Snehal-113 commented on Assignments/MYSQL/Priyanka/PriyankaDB1_1.sql
> +WHERE creditLimit between 70000
(creditLimit+2000) BETWEEN 70000 and 80000

2021-04-07 11:53 UTC, Snehal-113 commented on Assignments/MYSQL/Priyanka/PriyankaDB2.sql
> +WHERE (customerName LIKE 'J%' AND state != null);
state is not null

2021-04-07 11:53 UTC, Snehal-113 commented on Assignments/MYSQL/Priyanka/PriyankaDB2.sql
> +WHERE (customerName LIKE 'J%' AND state != null)
state is not null

2021-04-07 11:53 UTC, Snehal-113 commented on Assignments/MYSQL/Priyanka/PriyankaDB2.sql
> +WHERE (customerName LIKE 'J%' AND state != null)
state is not null

2021-04-07 14:03 UTC, yashubari approved these changes

2021-04-08 04:14 UTC, Snehal-113 approved these changes

2021-04-08 04:15 UTC, merged