uploading/Shivnanda Assesment
Snehal-113/MI-9-MEAN pull request #59
Opened 2020-11-30 02:54 UTC by shivnanda6272

2020-12-03 17:17 UTC, Snehal-113 reviewed
Good!

2020-12-03 17:17 UTC, Snehal-113 commented on Evaluation/Eval_28Nov20/ShivnandaE1.html
> +            <input type="tel" id="email" name="email" value="" placeholder="Email">
input type="email"

2020-12-04 10:02 UTC, Pawan1005 requested changes

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/ShivnandaA1/ShivnandaA1A4.html
> +        <h3><p>        I am basically from Nanded but currently staying in Pune. <br> I have done my graduation in BSC computer science and pursuing MSC computer science in Dr. d y patil college. </p
never use p tag in heading tag

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/ShivnandaA2/ShivnandaA2.html
> +        <h2><b> From the garage to the Googleplex </b></h2>
no need of b tag

2020-12-04 10:02 UTC, Pawan1005 commented on Evaluation/Eval_28Nov20/ShivnandaE1.html
> +            <input type="tel" id="phone" name="phone" value="" placeholder="Mobile Number" pattern="[0-9]{10}">
input type =number

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/ShivnandaA7_TP.html
> +</html>
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/ShivnandaA7_FP.html
> +        <input type="tel" id="mobile"name="mobile" placeholder="Mobile Number" required>
type= number

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/ShivnandaA7_5P.html
> +</center>
we dont use center as a tag

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/ShivnandaA7_5P.html
> +    <center>
center tag  older version

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/NaukriS.css
> +}
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign7/ShivnandaA7/ShivnandaA7_TP.html
> +</html>
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Evaluation/Eval_28Nov20/ShivnandaE1.css
> +}
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/Shivnanda6/ShivnandaA6.html
> +            <input type="radio" id="18_25" name="Age" value="18_25" checked>
wrong attribute

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/Shivnanda6/ShivnandaA6.html
> +            <input list="u" id="uni" name="uni"/>
no need of closing tag

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/Shivnanda6/ShivnandaA6.css
> +}
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/ShivnandaA5/ShivnandaA5Hobbies.html
> +    <body style="background-color: orangered;">
head tag missing

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/ShivnandaA5/Ass5.css
> +
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/ShivnandaA1/ShivnandaA1Q1.html
> +</html>
add new line

2020-12-04 10:02 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/ShivnandaA2/ShivnandaA2.html
> +
add new line

2020-12-09 10:36 UTC, merged