Vaibhav1
Snehal-113/MI-9-MEAN pull request #69
Opened 2020-11-30 11:37 UTC by vaibhavj18

2020-12-01 08:29 UTC, yashubari approved these changes

2020-12-09 07:17 UTC, Pawan1005 requested changes
check before push 
need to change every thing 
add indentation 
learn where we put css

2020-12-09 07:17 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/vaibhav/vpE1.html
> +
what is this

2020-12-09 07:17 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/vaibhav/vpE1.html
> +
what is this can you explain

2020-12-09 07:17 UTC, Pawan1005 commented on Evaluation/Eval_28Nov20/vaibhave1/vpE1.html
> +    <body text ="teal" bgcolor ="BLACK">
why 2 body tags

2020-12-09 10:40 UTC, merged