msg
Snehal-113/MI-9-MEAN pull request #73
Opened 2020-11-30 14:26 UTC by santoshinawkhare

2020-11-30 15:55 UTC, Manishnerkar approved these changes

2020-12-02 03:45 UTC, pradip1324 approved these changes

2020-12-08 09:24 UTC, Pawan1005 requested changes

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/santoshiA1/assignment A1.2.html
> +</html>
add new line

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/santoshiA1/assignmentA1.1html
> +</html>
add new line

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/santoshiA1/assignment A1.2.html
> +    <head><h1>HTML</h1></head>
need title here

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/santoshiA1/assignmentA1.1html
> +        <h1>HTML</h1>
need title here

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/santoshiA2/assignment2.html
> +    <head>
head tag closing

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/santoshiA2/assignment2.html
> +        </head>
remove head tag form here

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/santoshiA2/assignment2.html
> +</html>
add new line

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/santoshiA3/AssignmentA3.1.html
> +        a1{color:blue;}
wrong css

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/santoshiA6.html
> +       <centre><button>style="text-align: center;">Submit</button></centre>>
remove extra  > sign

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/santoshiA6.html
> +    <br></br>
no need of closing tag

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/santoshiA6.html
> +        <br></br>
no need of closing tag

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/santoshiA6.html
> +    </select><br></br>
no need of closing tag

2020-12-08 09:24 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/santoshiA6.html
> +        <br></br>
same here

2020-12-09 10:42 UTC, merged