Rajshri All Assi 1 to 6
Snehal-113/MI-9-MEAN pull request #80
Opened 2020-12-01 07:45 UTC by Rajashree07

2020-12-01 10:23 UTC, Pawan1005 requested changes
need indentation 
do correct all changes

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/ass1q2.html
> +<h4><pre> Web pages can be created and modified by using professional HTML editors.
for paragraph use p tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign1/ass1q4.html
> +<h2 style="background-color:yellow;">Self Introduction</h2>
use this in body tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/ass2.html
> +<head>
head tag closing missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/updated_ass2.html
> +</head>
wrong practice

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign2/updated_ass2.html
> +
remove extra lines

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/A3_1.html
> +</html>
what is use of a1 tag and a tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/A3_2.html
> +	  <p><h3>
how can you use h3 tag in p tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/RajMainA3_2.html
> +      <h3>Home Page</h3>
same mistake h3 in p tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/RajMainA3_2.html
> +        <h2 style="text-align: center;"></h2>
missing content

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/RajMainA3_2.html
> +     <h3>
p tag closing missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign3/Rajmi9A3_2.html
> +    <html>
double html tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign4/RajashreeAss4_1.html
> +        !-- border-collapse: collapse;
remove this extra

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign4/RajashreeAss4_1.html
> +
HTML closing missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign4/RajashreeAss4_1.html
> +        !-- border-collapse: collapse;
also from here

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign4/RajashreeAss4_2.html
> +        !-- border-collapse: collapse;
same mistake

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign4/RajashreeAss4_3.html
> +               <td style="background-color: rgb(229,233,21);"> 8:00 a.m.</th>
check closing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/CV.html
> +<title></title>
title missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/CV.html
> +<link type="text/css" rel="stylesheet" href="file:///home/shree/HTML/CV.css"/>
css file missing and use relative path

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/CV.html
> +            <p>
closing missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/RajashreeAss5.html
> +        </style>
opening missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/RajashreeAss5.html
> +        </head>
opening is missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/RajashreeAss5.html
> +        <div>
closing missing

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/RajashreeAss5.html
> +        <h3 class="format_font format head">
use p tag for paragraph

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/class.css
> +          <style>
wrong practice

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/class.css
> +          </style>
wrong practice

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/hobbies.html
> +</html>
add new line

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign5/hobbies.html
> +            <h1><b>My Hobbies</b></h1>
no need of b tag

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/RajashreeAss6.html
> +    <link type="text/css" rel="stylesheet" href="file:///home/shree/HTML/form.css">
use relative path

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/RajashreeAss6.html
> +</html>
add new line at end

2020-12-01 10:23 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign6/form.css
> +</style>
wrong practice

2020-12-02 03:43 UTC, pradip1324 approved these changes

2020-12-08 11:54 UTC, pradip1324 approved these changes

2020-12-08 14:51 UTC, Manishnerkar approved these changes

2020-12-09 10:51 UTC, merged