file added:Assignment 8
Snehal-113/MI-9-MEAN pull request #92
Opened 2020-12-10 09:54 UTC by Priyankashelke2411

2020-12-10 11:39 UTC, yashubari approved these changes

2020-12-10 13:13 UTC, Pawan1005 requested changes

2020-12-10 13:13 UTC, Pawan1005 commented on Assignments/HTML_CSS/Assign8/Priyanka/PriyankaA8.css
> +    width: 1000px;}
need indentation 
add extra line at end

2020-12-19 13:15 UTC, Pawan1005 approved these changes

2020-12-19 13:15 UTC, merged